title: "Leila Zhao "
email: "leilzhao853@gmail.com"
description: "BEng Mechanical Engineering @ HKU — aerospace design, CFD, DBF"
baseurl: "" # leave empty for user pages
url: "https://LeilaZhao.github.io"
theme: minima
