title: "Leila Zhao"
email: "leilzhao853@gmail.com"
description: "BEng Mechanical Engineering @ HKU — aerospace design, CFD, DBF"
baseurl: "" # leave empty for user pages
url: "https://Leilazehui.github.io"
theme: dinky


# _config.yml

